<?php
/**********************\
DON'T EDIT THIS FILE
USE THE SETTINGS EDITOR
\**********************/
$settings['adminemail'] = "prafullgs@yahoo.com";
$settings['blogname'] = "All about movies";
$settings['description'] = "Discussion Forum for Movies";
$settings['websitename'] = "Movies BB";
$settings['websiteurl'] = "www.cs.odu.edu/~pshirodk";
$settings['contactlink'] = "mailto:prafullgs@yahoo.com";
$settings['dateformat'] = "d-m-Y";
$settings['timeformat'] = "h:i A";
$settings['maindateformat'] = "l jS F Y";
$settings['timeoffset'] = "0";
$settings['numberrss'] = "10";
$settings['showeditedby'] = "";
$settings['display_posts'] ="";
$settings['display_comments'] = "";
$settings['version'] = "";
?>
